/**
 * `@cera/contracts` - the single source of truth for the platform's data shapes.
 *
 * Imported by producers, consumers, fixtures, and tests, so a breaking change
 * fails a build rather than a production request (PRD 8.1).
 *
 * Explicit re-exports rather than `export *`: a barrel that re-exports
 * everything makes it impossible to tell what is public API, and makes an
 * accidental export of an internal helper indistinguishable from an intentional
 * one.
 */

export {
  ALL_CUSTOMER_STATUSES,
  ALL_INTERNAL_STATUSES,
  allowedTransitionsFrom,
  buildCustomerTimeline,
  canTransition,
  CUSTOMER_STATUS_LABELS,
  CUSTOMER_STATUS_MAP,
  customerStatusLabel,
  evaluateTransition,
  INITIAL_INTERNAL_STATUS,
  INTERNAL_TRANSITIONS,
  isTerminalStatus,
  toCustomerStatus,
  type TransitionResult,
} from './status.ts';

export {
  type AuditTargetType,
  AuditTargetTypeSchema,
  type ContentType,
  ContentTypeSchema,
  type CustomerStatus,
  CustomerStatusSchema,
  type DeliveryStatus,
  DeliveryStatusSchema,
  type EnquirySource,
  EnquirySourceSchema,
  type IntegrationEventType,
  IntegrationEventTypeSchema,
  type IntegrationProvider,
  IntegrationProviderSchema,
  type InternalStatus,
  InternalStatusSchema,
  type OutboxStatus,
  OutboxStatusSchema,
  type PublicationStatus,
  PublicationStatusSchema,
  type Role,
  RoleSchema,
  type ServiceStatus,
  ServiceStatusSchema,
  STAFF_ROLES,
} from './enums.ts';

export {
  EmailSchema,
  EnquiryReferenceSchema,
  generateEnquiryReference,
  hashEmail,
  hashIp,
  hashToken,
  normaliseEmail,
  PhoneSchema,
  Sha256HexSchema,
  SlugSchema,
  SubjectIdSchema,
  UtcTimestampSchema,
  Uuidv7Schema,
} from './primitives.ts';

export {
  type AuditEvent,
  AuditEventSchema,
  CLAIM_TOKEN_TTL_MINUTES,
  type ContentDocument,
  ContentDocumentSchema,
  type CustomerProfile,
  CustomerProfileSchema,
  type CustomerProfileUpdate,
  CustomerProfileUpdateSchema,
  type Enquiry,
  type EnquiryClaimToken,
  EnquiryClaimTokenSchema,
  type EnquiryInput,
  EnquiryInputSchema,
  EnquirySchema,
  ENQUIRY_CONSENT_VERSION,
  type EnquiryStatusEvent,
  EnquiryStatusEventSchema,
  requiredServiceSpecificConsent,
  type ServiceSpecificConsentField,
  type IntegrationDelivery,
  IntegrationDeliverySchema,
  type InternalNote,
  InternalNoteSchema,
  type OutboxRecord,
  OutboxRecordSchema,
  PROHIBITED_ENQUIRY_FIELDS,
  type SafeDiff,
  SafeDiffSchema,
  SeoSchema,
  type Service,
  ServiceCategorySchema,
  ServiceSchema,
} from './entities.ts';

export {
  type CustomerEnquiry,
  CustomerEnquirySchema,
  CustomerTimelineEntrySchema,
  type PublicService,
  PublicServiceSchema,
  splitName,
  type StaffEnquiry,
  StaffEnquirySchema,
  toCustomerEnquiry,
  toPublicService,
  toStaffEnquiry,
  toCrmLeadPayload,
  type CrmLeadPayload,
  CrmLeadPayloadSchema,
} from './projections.ts';

export {
  ApiError,
  buildErrorEnvelope,
  type BuildErrorOptions,
  DEFAULT_ERROR_MESSAGES,
  type ErrorCode,
  ErrorCodeSchema,
  type ErrorEnvelope,
  ErrorEnvelopeSchema,
  type FieldError,
  FieldErrorSchema,
  fieldErrorsFromZod,
  HTTP_STATUS_BY_ERROR_CODE,
  httpStatusFor,
} from './errors.ts';

export {
  buildPage,
  type Cursor,
  CursorSchema,
  decodeCursor,
  DEFAULT_PAGE_SIZE,
  encodeCursor,
  MAX_PAGE_SIZE,
  type Page,
  PageSchema,
  type PaginationQuery,
  PaginationQuerySchema,
} from './pagination.ts';

export { PREVIEW_TTL_SECONDS, signPreviewToken, verifyPreviewToken } from './preview-token.ts';

export {
  ALL_SESSION_COOKIE_NAMES,
  OIDC_STATE_COOKIE_NAME,
  SESSION_COOKIE_NAME,
  type SessionCookieName,
} from './session.ts';

export {
  AssignEnquiryRequestSchema,
  AuditEntrySchema,
  ClaimConsumeRequestSchema,
  ClaimConsumeResponseSchema,
  ClaimRequestResponseSchema,
  ClaimRequestSchema,
  ContentParamsSchema,
  ContentResponseSchema,
  CreateEnquiryRequestSchema,
  type CreateEnquiryResponse,
  CreateEnquiryResponseSchema,
  CreateNoteRequestSchema,
  DeliveryListItemSchema,
  type ListDeliveriesQuery,
  ListDeliveriesQuerySchema,
  ListDeliveriesResponseSchema,
  ListAuditQuerySchema,
  ListAuditResponseSchema,
  ListMyEnquiriesQuerySchema,
  ListMyEnquiriesResponseSchema,
  ListNotesResponseSchema,
  type ListOpsEnquiriesQuery,
  ListOpsEnquiriesQuerySchema,
  ListOpsEnquiriesResponseSchema,
  type ListServicesQuery,
  ListServicesQuerySchema,
  ListServicesResponseSchema,
  ListStatusEventsResponseSchema,
  MyEnquiryParamsSchema,
  type MyProfileResponse,
  MyProfileResponseSchema,
  OPS_ENQUIRY_SORTS,
  OpsEnquiryParamsSchema,
  type ResendWebhookEvent,
  ResendWebhookEventSchema,
  RetryDeliveryParamsSchema,
  RetryDeliveryResponseSchema,
  type SearchQuery,
  SearchQuerySchema,
  type SearchHit,
  SearchHitSchema,
  SearchResponseSchema,
  ServiceParamsSchema,
  type TransitionEnquiryRequest,
  TransitionEnquiryRequestSchema,
  TransitionEnquiryResponseSchema,
  UpdateMyProfileRequestSchema,
  WebhookAckResponseSchema,
} from './api.ts';

export type { CrmPort, CrmUpsertResult, EmailMessage, EmailPort, StoragePort } from './ports.ts';
