/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    policies: Policy;
    'service-presentations': ServicePresentation;
    redirects: Redirect;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    'service-presentations': ServicePresentationsSelect<false> | ServicePresentationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    announcement: Announcement;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'content_editor' | 'content_approver' | 'operations_manager' | 'enquiry_handler' | 'administrator' | 'auditor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required. Describe the image for someone who cannot see it. Decorative images still need a short honest label, not an empty string.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Lower-case, hyphenated. Becomes the public URL.
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Published but not indexed. Preview is always noindex.
     */
    noIndex?: boolean | null;
  };
  /**
   * Flag this draft for an approver. Does not publish it.
   */
  reviewRequested?: boolean | null;
  authorId?: string | null;
  approverId?: string | null;
  publishedAt?: string | null;
  fixture?: boolean | null;
  excerpt?: string | null;
  /**
   * Build pages from approved, accessible sections. Every available block is rendered on the public site.
   */
  layout?:
    | (
        | {
            eyebrow: string;
            headlinePrimary: string;
            headlineAccent: string;
            body: string;
            primaryHref: string;
            primaryLabel: string;
            secondaryHref: string;
            secondaryLabel: string;
            portrait?: (number | null) | Media;
            badgeTitle?: string | null;
            badgeBody?: string | null;
            trustItems?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            badges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionHeading';
          }
        | {
            searchLabel?: string | null;
            applyLabel?: string | null;
            emptyHeading?: string | null;
            emptyDescription?: string | null;
            degradedAlert?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesCatalogue';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            tone?: ('surface' | 'surface-tint' | 'surface-tint-2') | null;
            /**
             * Centre the section heading (audience-style bands).
             */
            centered?: boolean | null;
            features: {
              title: string;
              description: string;
              href?: string | null;
              linkLabel?: string | null;
              highlights?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            tone?: ('surface' | 'surface-tint' | 'surface-tint-2') | null;
            variant?: ('grid' | 'timeline' | 'numbered') | null;
            steps: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'processSteps';
          }
        | {
            heading?: string | null;
            body?: string | null;
            items: {
              value: string;
              label: string;
              detail?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            heading: string;
            body?: string | null;
            viewAllHref?: string | null;
            viewAllLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesShowcase';
          }
        | {
            heading: string;
            body?: string | null;
            viewAllHref?: string | null;
            viewAllLabel?: string | null;
            maxPosts?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articlesPreview';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            linkHref?: string | null;
            linkLabel?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBand';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            headline: string;
            body?: string | null;
            href: string;
            label: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
        | {
            eyebrow?: string | null;
            badges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            noticeTitle?: string | null;
            noticeBody?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceHero';
          }
        | {
            heading: string;
            body?: string | null;
            items: {
              label: string;
              detail?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'keyValueList';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            body?: string | null;
            buttonLabel?: string | null;
            trustItems?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceEnquiryAside';
          }
        | {
            title: string;
            body?: string | null;
            items?:
              | {
                  label: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceSidebarCard';
          }
      )[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Lower-case, hyphenated. Becomes the public URL.
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Published but not indexed. Preview is always noindex.
     */
    noIndex?: boolean | null;
  };
  /**
   * Flag this draft for an approver. Does not publish it.
   */
  reviewRequested?: boolean | null;
  authorId?: string | null;
  approverId?: string | null;
  publishedAt?: string | null;
  fixture?: boolean | null;
  excerpt: string;
  cover?: (number | null) | Media;
  category: number | Category;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Lower-case, hyphenated. Becomes the public URL.
   */
  slug: string;
  /**
   * A theme.css token, not a colour. The pill is drawn in that token.
   */
  colourToken: 'accent-fill' | 'primary' | 'accent' | 'foreground';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  title: string;
  /**
   * Lower-case, hyphenated. Becomes the public URL.
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Published but not indexed. Preview is always noindex.
     */
    noIndex?: boolean | null;
  };
  /**
   * Flag this draft for an approver. Does not publish it.
   */
  reviewRequested?: boolean | null;
  authorId?: string | null;
  approverId?: string | null;
  publishedAt?: string | null;
  fixture?: boolean | null;
  excerpt?: string | null;
  /**
   * Shown as the document date. Changing it is a new version.
   */
  effectiveDate: string;
  versionLabel: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-presentations".
 */
export interface ServicePresentation {
  id: number;
  title: string;
  /**
   * Lower-case, hyphenated. Becomes the public URL.
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Published but not indexed. Preview is always noindex.
     */
    noIndex?: boolean | null;
  };
  /**
   * Flag this draft for an approver. Does not publish it.
   */
  reviewRequested?: boolean | null;
  authorId?: string | null;
  approverId?: string | null;
  publishedAt?: string | null;
  fixture?: boolean | null;
  /**
   * Vendure product id, or the slug until Phase 06. Validated against the live catalogue on save.
   */
  serviceId: string;
  excerpt?: string | null;
  /**
   * Optional bullets on service catalogue and homepage cards.
   */
  cardHighlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Icon on catalogue and homepage service cards.
   */
  cardIcon?: ('microscope' | 'dna' | 'database' | 'chart' | 'fileText') | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Service (catalogue) page sections: hero, capability grids, lifecycle steps, sidebar enquiry card, and specifications. Vendure supplies price and availability.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            badges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            noticeTitle?: string | null;
            noticeBody?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceHero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            badges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionHeading';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            tone?: ('surface' | 'surface-tint' | 'surface-tint-2') | null;
            /**
             * Centre the section heading (audience-style bands).
             */
            centered?: boolean | null;
            features: {
              title: string;
              description: string;
              href?: string | null;
              linkLabel?: string | null;
              highlights?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            tone?: ('surface' | 'surface-tint' | 'surface-tint-2') | null;
            variant?: ('grid' | 'timeline' | 'numbered') | null;
            steps: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'processSteps';
          }
        | {
            heading: string;
            body?: string | null;
            items: {
              label: string;
              detail?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'keyValueList';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBand';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            linkHref?: string | null;
            linkLabel?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            body?: string | null;
            buttonLabel?: string | null;
            trustItems?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceEnquiryAside';
          }
        | {
            title: string;
            body?: string | null;
            items?:
              | {
                  label: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceSidebarCard';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actorSubjectId?: string | null;
  action: string;
  targetType: string;
  targetId: string;
  safeDiff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'service-presentations';
        value: number | ServicePresentation;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  reviewRequested?: T;
  authorId?: T;
  approverId?: T;
  publishedAt?: T;
  fixture?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headlinePrimary?: T;
              headlineAccent?: T;
              body?: T;
              primaryHref?: T;
              primaryLabel?: T;
              secondaryHref?: T;
              secondaryLabel?: T;
              portrait?: T;
              badgeTitle?: T;
              badgeBody?: T;
              trustItems?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sectionHeading?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesCatalogue?:
          | T
          | {
              searchLabel?: T;
              applyLabel?: T;
              emptyHeading?: T;
              emptyDescription?: T;
              degradedAlert?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              tone?: T;
              centered?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    linkLabel?: T;
                    highlights?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              tone?: T;
              variant?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesShowcase?:
          | T
          | {
              heading?: T;
              body?: T;
              viewAllHref?: T;
              viewAllLabel?: T;
              id?: T;
              blockName?: T;
            };
        articlesPreview?:
          | T
          | {
              heading?: T;
              body?: T;
              viewAllHref?: T;
              viewAllLabel?: T;
              maxPosts?: T;
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              linkHref?: T;
              linkLabel?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calloutBand?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              headline?: T;
              body?: T;
              href?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
        serviceHero?:
          | T
          | {
              eyebrow?: T;
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              noticeTitle?: T;
              noticeBody?: T;
              id?: T;
              blockName?: T;
            };
        keyValueList?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceEnquiryAside?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              buttonLabel?: T;
              trustItems?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceSidebarCard?:
          | T
          | {
              title?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  reviewRequested?: T;
  authorId?: T;
  approverId?: T;
  publishedAt?: T;
  fixture?: T;
  excerpt?: T;
  cover?: T;
  category?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  colourToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  reviewRequested?: T;
  authorId?: T;
  approverId?: T;
  publishedAt?: T;
  fixture?: T;
  excerpt?: T;
  effectiveDate?: T;
  versionLabel?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-presentations_select".
 */
export interface ServicePresentationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  reviewRequested?: T;
  authorId?: T;
  approverId?: T;
  publishedAt?: T;
  fixture?: T;
  serviceId?: T;
  excerpt?: T;
  cardHighlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cardIcon?: T;
  body?: T;
  layout?:
    | T
    | {
        serviceHero?:
          | T
          | {
              eyebrow?: T;
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              noticeTitle?: T;
              noticeBody?: T;
              id?: T;
              blockName?: T;
            };
        sectionHeading?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              tone?: T;
              centered?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    linkLabel?: T;
                    highlights?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              tone?: T;
              variant?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        keyValueList?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calloutBand?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              linkHref?: T;
              linkLabel?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceEnquiryAside?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              buttonLabel?: T;
              trustItems?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceSidebarCard?:
          | T
          | {
              title?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actorSubjectId?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  safeDiff?: T;
  requestId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tagline?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  contactLocations?:
    | {
        label: string;
        value: string;
        href?: string | null;
        icon?: ('mail' | 'mapPin' | 'phone') | null;
        id?: string | null;
      }[]
    | null;
  contactEnquiry?: {
    heading?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
    formSectionTitle?: string | null;
    /**
     * When enabled, the full enquiry form appears on the Contact page.
     */
    showInlineForm?: boolean | null;
  };
  social?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  newsletterHeading?: string | null;
  newsletterBody?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  enquiryForm: {
    consentVersion: string;
    generalConsent: string;
    sequencingConsent?:
      | {
          statement: string;
          id?: string | null;
        }[]
      | null;
    samplesConsent?:
      | {
          statement: string;
          id?: string | null;
        }[]
      | null;
    healthDataConsent?:
      | {
          statement: string;
          id?: string | null;
        }[]
      | null;
    updatesOptIn?: string | null;
    contactNotice?: string | null;
    successMessage?: string | null;
    fieldLabels?: {
      name?: string | null;
      email?: string | null;
      phone?: string | null;
      institution?: string | null;
      country?: string | null;
      serviceId?: string | null;
      message?: string | null;
      submit?: string | null;
    };
    fieldHints?: {
      email?: string | null;
      serviceLocked?: string | null;
      message?: string | null;
    };
    retentionFooter?: string | null;
    /**
     * Additional enquiry dropdown options (non-catalogue).
     */
    extraServices?:
      | {
          slug: string;
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: number;
  enabled?: boolean | null;
  /**
   * Short label beside the pulse indicator (e.g. Lab accredited).
   */
  statusLabel?: string | null;
  /**
   * Supporting line shown from tablet width upward.
   */
  message?: string | null;
  /**
   * Optional link target (e.g. /methodology).
   */
  href?: string | null;
  /**
   * Optional link text (e.g. Review protocol standards).
   */
  linkLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tagline?: T;
  email?: T;
  phone?: T;
  address?: T;
  contactLocations?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  contactEnquiry?:
    | T
    | {
        heading?: T;
        body?: T;
        buttonLabel?: T;
        buttonHref?: T;
        formSectionTitle?: T;
        showInlineForm?: T;
      };
  social?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  newsletterHeading?: T;
  newsletterBody?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  enquiryForm?:
    | T
    | {
        consentVersion?: T;
        generalConsent?: T;
        sequencingConsent?:
          | T
          | {
              statement?: T;
              id?: T;
            };
        samplesConsent?:
          | T
          | {
              statement?: T;
              id?: T;
            };
        healthDataConsent?:
          | T
          | {
              statement?: T;
              id?: T;
            };
        updatesOptIn?: T;
        contactNotice?: T;
        successMessage?: T;
        fieldLabels?:
          | T
          | {
              name?: T;
              email?: T;
              phone?: T;
              institution?: T;
              country?: T;
              serviceId?: T;
              message?: T;
              submit?: T;
            };
        fieldHints?:
          | T
          | {
              email?: T;
              serviceLocked?: T;
              message?: T;
            };
        retentionFooter?: T;
        extraServices?:
          | T
          | {
              slug?: T;
              title?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  enabled?: T;
  statusLabel?: T;
  message?: T;
  href?: T;
  linkLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'policies';
          value: number | Policy;
        } | null)
      | ({
          relationTo: 'service-presentations';
          value: number | ServicePresentation;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}